server:
  port: 0

spring:
  application:
    name: product-service
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ${DB_ORACLE_URL}
    username: ${DB_ORACLE_USERNAME}
    password: ${DB_ORACLE_PASSWORD}
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 16
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: none
   
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
